name: Auto approve and merge 
on: 
  pull_request:
    branches:
    - master

jobs:
  logs4netlify:
    name: Logs for Netlify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy Logs
      uses: bdougie/loglify@master
  auto-merge:
    needs: logs4netlify
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Label when approved
      uses: bdougie/label-when-approved-action@master
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "automerge"
    - name: automerge
      uses: bdougie/automerge-action@bot
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
