<<<<<<< HEAD
name: Auto approve
on: pull_request
=======
name: Auto approve and merge 
on: 
  pull_request:
    branches:
    - master
>>>>>>> a1e0d5a... copy and images

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
