name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    
    steps:
    - name: Wait for check to succeed
      uses: fountainhead/action-wait-for-check@v1.0.0
      id: wait-for-build
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: netlify
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      if: steps.wait-for-build.outputs.conclusion == 'success'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      if: steps.wait-for-build.outputs.conclusion == 'success'
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
