on: pull_request_review
name: automerge pull requests on reviews
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "2"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "automerge"
    - name: automerge
      uses: pascalgn/automerge-action@33f73f0a562129c7e96123e98af20d4378f1fa3b
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
